import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

import { Providers } from "./providers";
import { Sidebar } from "./_components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "500", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className} suppressHydrationWarning>
      <Providers>
        <body>
          <div className="min-h-full min-w-full">
            <Sidebar>{children}</Sidebar>
          </div>
        </body>
      </Providers>
    </html>
  );
}
