import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body>
          <div className="flex min-h-full items-stretch justify-between">
            <div className="flex flex-col w-96 bg-primary p-2 min-h-full items-start justify-start">
              <Link href="/" className="text-secondary">
                Home Page
              </Link>
              <Link href="/burak" className="text-secondary">
                Burak
              </Link>
              <button className="btn btn-warning">Button</button>
            </div>
            <div className="flex-1 min-h-full bg-secondary">{children}</div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
